os: linux
dist: focal
arch: amd64
language: java
jdk: openjdk17
cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

addons:
  hosts:
    - personal-pass.dev
  sonarcloud:
    organization: "ya84p9jfkc2z4jv3hzcbdrmg2ffmjgw8"
#    token:
#      secure: "$SONAR_TOKEN"


env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=Dominik1984

branches:
  only:
    - master
    - development

before_install:
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - sudo wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install language-pack-pl
  - sudo apt-get -y install postgresql-14 postgresql-client-14
  - sudo /etc/init.d/postgresql start 14.0

before_script:
  - psql --file travis-database.sql

jobs:
  include:
    - stage: Unit Tests
      script: ./mvnw test -B -Dmaven.javadoc.skip=true
    - stage: Integration Tests
      script: ./mvnw verify -B -Dmaven.javadoc.skip=true
      after_success:
        - ./mvnw jacoco:report coveralls:report sonar:sonar -Dsonar.projectKey=personal_pass_project
        - bash <(curl -s https://codecov.io/bash)