os: linux
dist: focal
arch: amd64
language: java
jdk: openjdk17
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - development

after_success:
  - ./mvnw jacoco:report coveralls:report