os: linux
dist: focal
arch: amd64
language: java
jdk: openjdk17
cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

#addons:
#  postgresql: "14.0"
#  apt:
#    packages:
#      - postgresql-14
#      - postgresql-client-14

env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=Dominik1984

#branches:
#  only:
#    - master
#    - development

before_install:
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - sudo wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install postgresql-14 postgresql-client-14
  - sudo /etc/init.d/postgresql start 14.0

before_script:
  - psql --file travis-database.sql
after_success:
  - ./mvnw jacoco:report coveralls:report